name: Publish Maven to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish-package:
    # Полагаем, что без токенов наш Gradle публиковать не умеет никуда.
    # А в данном случае мы ему даём GITHUB_PKGPUB_TOKEN, и он сориентируется,
    # что публикуем в GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      - name: Publish
        run:
          ./gradlew publish
        env:
          # the secrets.GITHUB_TOKEN is predefined
          GITHUB_PKGPUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}